### ISSUE TITLE
array-slice-ref returns different values in racket and typed-racket

### ISSUE THREAD

**Issue by donm** [racket/math#13]
Running the following example with `#lang typed/racket` and `#lang racket` results in two different answers, where the `#lang racket` behavior appears to be incorrect.  
```
(require math/array)
(define arr (array #[#[1 2 3] #[4 5 6]]))
(array-slice-ref arr (list 0 ::...))
;; #lang typed/racket -> (array #[1 2 3])
;; #lang racket       -> (array #[])
```
I tested this in Racket v6.9 on Linux and Racket v6.11 on macOS and it occurs in both.

**Comment by samth** [comment]
This is probably because `array-slice-ref` has a polymorphic type, producing some wrapper, which then causes `array-slice-ref` to not do the right thing.

**Comment by mfelleisen** [comment]
@ samth 

Hah! A proof of my conjecture with an example 'from the wild’.

**Comment by pnwamk** [comment]
It's an issue with confusing `Integer` and `(Sequenceof Integer)`. An `Integer` is a `(Sequenceof Integer)` (well when it's an `exact-nonnegative-integer?` anyways), but contract generation is currently wrapping the `0` in a sequence contract instead of leaving it alone as it should.

Here is a (minimal?) example:

```racket
#lang racket/base

(module typed typed/racket/base
  (provide foo)
  (: foo (-> (U Integer (Sequenceof Integer)) String))
  (define (foo x)
    (if (integer? x)
        (format "I got an integer: ~a" x)
        (format "I did not get an integer: ~a" x))))

(module other-typed typed/racket/base
  (provide bar)
  (require (submod ".." typed))
  (define (bar) (foo 0)))

(require 'typed
         'other-typed)
(foo 0)
(bar)
```

produces

```
"I did not get an integer: #<sequence>"
"I got an integer: 0"
```

**Comment by samth** [comment]
Currently, `sequence/c` unconditionally wraps with a sequence (as documented). 

@rfindler What would you think of changing this to be something with more possibilites, so that

```
(contract (sequence/c exact-integer?) 5 'pos 'neg)
```

produced `5`?

**Comment by pnwamk** [comment]
Here is a related program with no types that uses contracts similar to what Typed Racket uses to guard `foo` in the previous example:

```racket
#lang racket/base

(module untyped racket/base
  (require racket/contract
           racket/sequence)
  (provide (contract-out [baz (-> (or/c (and/c exact-integer? negative?)
                                        (sequence/c exact-integer?))
                                  string?)]))
  (define (baz x)
    (if (integer? x)
        (format "I got an integer: ~a" x)
        (format "I did not get an integer: ~a" x))))

(require 'untyped)

(baz 0)
```

produces

```
"I did not get an integer: #<sequence>"
```

In other words, Typed Racket, after simplifying the union `(U Integer (Sequenceof Integer))` to remove overlapping types gets the type `(U Negative-Integer (Sequenceof Integer))`, which is converted into the contract:

```
(or/c (and/c exact-integer? negative?)
      (sequence/c exact-integer?))
```

Which will wrap the value `0` in a `sequence/c` contract.

**Comment by rfindler** [comment]
I think that `sequence/c` is not the contract you want to use here. That much seems clear. 

I'm not sure how we can reasonably change sequence/c to return only the integer in this case (because it would have to be able to predict how arbitrary predicates work on integers and other built-in values that are sequences). I think that TR has to just avoid the non-chaperone nature of sequence/c. In other words, I think the right solution here is that the simplification that @pnwamk describes is invalid and to generate a contract like this:

```
(contract (or/c integer? (sequence/c integer?))
          5
          'pos 'neg)
```

**Comment by samth** [comment]
Ok, I wrote the straightforward fix here in TR; merge pending tests passing.
