### ISSUE TITLE
(modular-inverse 0 1) is well-defined

### ISSUE THREAD

**Issue by sorawee** [racket/math#53]
Z/1Z is the [zero ring](https://en.wikipedia.org/wiki/Zero_ring) where 0 = 1. Therefore, `(modular-inverse 0 1)` should return 0, not an error.

**Comment by pavpanchekha** [comment]
I guess I see the argument for, but honestly "what does this do modulo 1" is a not a question with an obvious answer, so I think it might be better to return an error. It satisfies some properties (like `inv * 0 = 1 mod 1`) but not others (`inv * 0 mod 1 = 1`). The trivial ring isn't even considered a ring in all contexts!

Since the workaround is so easy, I think it's better not to make the implied change.
