### ISSUE TITLE
`quadratic-discriminant` loses accuracy for some inputs

### ISSUE THREAD

**Issue by goualard-f** [racket/math#83]
The `quadratic-discriminant` function used in `quadratic-solutions` does not compute the discriminant with full accuracy for some inputs.
Consider the equation $-312499999999x^2+707106781186x-400000000000=0$ from [Nievergelt's paper](https://www.tandfonline.com/doi/abs/10.1080/07468342.2003.11921990?journalCode=ucmj20). It has two close solutions around $1.13$, while `quadratic-solutions` reports that there is none. 

Consider also the equation $F(n)x^2-2F(n-1)x+F(n-2)=0$, with $F$ the Fibonacci function. As presented by [Kahan](https://people.eecs.berkeley.edu/~wkahan/Qdrtcs.pdf), it should have the two solutions $\frac{F(n-1)\pm\sqrt{(-1)^n}}{F(n)}$. For $n=34$, we get $5702887x^2-7049156x+2178309=0$. If we solve the equation with integers, we get the correct results, otherwise we get none:
```racket
> (quadratic-solutions 5702887 -7049156 2178309)
'(987/1597 2207/3571)
> (quadratic-solutions 5702887.0 -7049156.0 2178309.0)
'()
```

**Comment by pavpanchekha** [comment]
You know, I was going to complain about how this is pretty edge-case stuff and how our quadratic isn't guaranteed to be exactly rounded and therefore how this was a wontfix, but luckily I felt a sense of duty and decided to investigate just in case it was a real bug—and it was!

You can see the solution in #85, basically a double-double division computed the error term wrong and that was causing the issue here. Thanks for the bug report!
