### ISSUE TITLE
In math/number-theory, the current modulus should change inside an exponent

### ISSUE THREAD

**Issue by cooljoseph1** [racket/math#94]
Right now, the `with-modulus` environment sets a modulus and this is the same modulus for all operations inside the environment. However, I think that the modulus should change when exponentiation is used, since the correct modulus for the exponent is different than for the base.

For example, I think that
```racket
(with-modulus 11
    (modexpt 2 (modexpt 2 8)))
```
should be equivalent to

```racket
(modular-expt 2 (modular-expt 2 8
                              10)
              11)
```
where the modulus is 10 in the exponent instead of 11. Right now
```racket
(with-modulus 11
    (modexpt 2 (modexpt 2 8)))
```
is the same as
```racket
(modular-expt 2 (modular-expt 2 8
                              11)
              11)
```
instead.

The reason for this change is that as a user, I would expect
```racket
(modexpt 2 (modexpt 2 8))
```
to be the same as
```racket
(expt 2 (expt 2 8))
```
except that the result is taken modulo the base modulus.

-------

This could be implemented by changing the current modulus $n$ to be $\lambda(n)$ for any modular arithmetic in the exponent, where $\lambda$ is the Carmichael function. (Alternatively, you could use the Euler totient function--which might be the better choice since we already have the totient function implemented.)

**Comment by cooljoseph1** [comment]
Alternatively, add the following macro:
```
(define-syntax-rule (modexpt* a b)
  (modexpt a
           (with-modulus (totient (current-modulus))
             b)))
```

The \* is to emphasize that it is for a nested modular exponentiation.

**Comment by soegaard** [comment]
You have found an interesting case.

In a symbolic algebra program the macro solution could be applied.
However, here where `modexpect` is a function, evaluation happens inside-out,
so the outer exponentiation can't affect the inner one.

I don't see a better solution than using `module-expt` in the exponent
or to use nested `with-modulus` to change the modulus used in the exponent.

An alternative is to introduce an `modexp*` for repeated exponentation.

So instead of:
```
(with-modulus 11
    (modexpt 2 (modexpt 2 8)))
```
One could write:
```
(with-modulus 11
    (modexpt* 2 2 8))
```    
And then `modexpt*` could calculate the moduli needed for the calcuation.
